//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BKBVehicleEntities : DbContext
    {
        public BKBVehicleEntities()
            : base("name=BKBVehicleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<branchbb> branchbbs { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<MainMenu> MainMenus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleMenuMapping> RoleMenuMappings { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
        public virtual DbSet<UserRegionmapping> UserRegionmappings { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<LoginUser> LoginUsers { get; set; }
        public virtual DbSet<Fuel_Details_Table> Fuel_Details_Table { get; set; }
        public virtual DbSet<Maintenance> Maintenances { get; set; }
        public virtual DbSet<Car_Details> Car_Details { get; set; }
        public virtual DbSet<Car_Info> Car_Info { get; set; }
        public virtual DbSet<EmployeeInfo> EmployeeInfoes { get; set; }
        public virtual DbSet<InputList> InputLists { get; set; }
        public virtual DbSet<Repair> Repairs { get; set; }
        public virtual DbSet<Varities_Table> Varities_Table { get; set; }
        public virtual DbSet<RepairDetail> RepairDetails { get; set; }

        public System.Data.Entity.DbSet<BKBVehicle.Models.VehicleAppModel.CarInfoViewModel> CarInfoViewModels { get; set; }
    }
}
