//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class branchbb
    {
        public Nullable<double> SLNO { get; set; }
        public string BranchName { get; set; }
        public string BBcode { get; set; }
        public string BKBcode { get; set; }
        public string brname { get; set; }
        public string Region { get; set; }
        public string PARTICULARS { get; set; }
        public string RegionCode { get; set; }
        public int id { get; set; }
    }
}
