//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int id { get; set; }
        public string branch_code { get; set; }
        public string branch_name { get; set; }
        public string region { get; set; }
        public string BBCode { get; set; }
        public string RoutingNo { get; set; }
        public string agentID { get; set; }
        public string agentSequence { get; set; }
        public string token { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string MainOffice { get; set; }
        public string Status { get; set; }
        public string StoreNum { get; set; }
        public string ISO { get; set; }
        public string ZIP { get; set; }
        public string POSStatus { get; set; }
        public string UnitProfileID { get; set; }
        public string AgentPIN { get; set; }
        public string RAMS { get; set; }
        public string Partyno { get; set; }
        public string HQPartyno { get; set; }
        public string UnitOffice { get; set; }
        public string Legacy { get; set; }
        public int bankID { get; set; }
        public string XPreceivingagentcode { get; set; }
        public Nullable<int> Acc_ID { get; set; }
        public string branch_name_BN { get; set; }
    
        public virtual Bank Bank { get; set; }
    }
}
