//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Details
    {
        public int id { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<System.DateTime> TaxToken { get; set; }
        public Nullable<System.DateTime> Fitness { get; set; }
        public Nullable<System.DateTime> RoutePermit { get; set; }
        public Nullable<System.DateTime> Insurance { get; set; }
        public Nullable<decimal> Depriciation { get; set; }
        public Nullable<decimal> BookValue { get; set; }
        public string Remarks { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Flag { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> BookValueDate { get; set; }
        public string BrCode { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedStatus { get; set; }
    }
}
