//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_Info
    {
        public int id { get; set; }
        public string VehicleType { get; set; }
        public string RegistrationNo { get; set; }
        public string BrandName { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> ProductionYear { get; set; }
        public string Color { get; set; }
        public string ChesisNo { get; set; }
        public string EngineNo { get; set; }
        public Nullable<decimal> PurchaseValue { get; set; }
        public string Remarks { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Flag { get; set; }
        public string OfficeName { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string BrCode { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedStatus { get; set; }
    }
}
