//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public int id { get; set; }
        public string countryName { get; set; }
        public string countryCode { get; set; }
        public string countryLegacyCode { get; set; }
        public string baseReceiveCurrency { get; set; }
    }
}
