//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel_Details_Table
    {
        public int id { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<System.DateTime> FuelDate { get; set; }
        public Nullable<decimal> FuelConsumptionCost { get; set; }
        public string Remarks { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Flag { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string FuelType { get; set; }
        public Nullable<int> FuelComsumptionQ { get; set; }
        public string UsedBy { get; set; }
        public string Driver { get; set; }
        public string UsedByPF { get; set; }
        public string DriverPF { get; set; }
        public string Degination { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> FuelQuantity { get; set; }
        public string BrCode { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovedStatus { get; set; }
    }
}
