//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginUser
    {
        public string userID { get; set; }
        public string userPass { get; set; }
        public string userName { get; set; }
        public int userRole { get; set; }
        public string branch_code { get; set; }
        public string user_status { get; set; }
        public string first_login { get; set; }
        public string makerID { get; set; }
        public Nullable<System.DateTime> makerTime { get; set; }
        public string checkerID { get; set; }
        public Nullable<System.DateTime> checkerTime { get; set; }
        public string updatedBY { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string UserMobile { get; set; }
        public int bankID { get; set; }
        public Nullable<long> user_id { get; set; }
    
        public virtual Bank Bank { get; set; }
    }
}
