//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMenuMapping
    {
        public int ID { get; set; }
        public int UserRoleId { get; set; }
        public int SubMenuId { get; set; }
        public string IsActive { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual SubMenu SubMenu { get; set; }
    }
}
