//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BKBVehicle.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varities_Table
    {
        public int id { get; set; }
        public string Value { get; set; }
        public string Label { get; set; }
        public string Field { get; set; }
        public Nullable<int> Flag { get; set; }
        public string Type { get; set; }
    }
}
